# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  jhipster_redis_demo-app:
    image: jhipster_redis_demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster_redis_demo-postgresql:5432/jhipster_redis_demo
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://jhipster_redis_demo-postgresql:5432/jhipster_redis_demo
      - JHIPSTER_CACHE_REDIS_SERVER=redis://jhipster_redis_demo-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://jhipster_redis_demo-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  jhipster_redis_demo-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/jhipster_redis_demo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipster_redis_demo
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
  jhipster_redis_demo-redis:
    image: redis:6.2.7
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
